#!/bin/sh
# Xsetup - run as root before the login dialog appears
xrandr --output DP-2 --off
xrandr --output DP-1 --mode 2560x1440 --pos 0x0 --rotate normal

#Goes in /usr/share/sddm/scripts/Xsetup
#Makes it so SDDM only starts on the main monitor.